### ISSUE TITLE
Comply with pylint

### ISSUE THREAD

**Issue by vdmkenny** [vdmkenny/cine-aalst-cli#1]
Currently pylint is showing many warnings and errors.

**Comment by Microturbine** [comment]
I am a beginner but would like to make a few modifications as a learning experience.
I found two problems with pylint, so I fixed those.
I will send you a pull request so you can take a look if you like.

**Comment by vdmkenny** [comment]
Thanks @Microturbine and sorry for the late response, I did not see your comment.
I will have a look in the morning!

**Comment by vdmkenny** [comment]
I have made some changes and ignored some pylint errors. It now scores 10/10.
